from unittest import TestCase

from parse_cobol_rec.parse_cobol_claude import generate_substr_from_file


class Test(TestCase):
    def test_generate_substr_from_file(self):
        output = generate_substr_from_file('input1.txt')
        self.assertEqual(output,
'''CAST(SUBSTR(WS_DTAQ_MESSAGE, 1, 3) AS CHAR(3) CCSID 37) AS FLD1,
CAST(SUBSTR(WS_DTAQ_MESSAGE, 4, 5) AS CHAR(5) CCSID 37) AS FLD2,
INTERPRET(CAST(SUBSTR(WS_DTAQ_MESSAGE, 9, 5) AS BINARY(5)) AS NUMERIC(5, 2)) AS FLD3,
INTERPRET(CAST(SUBSTR(WS_DTAQ_MESSAGE, 14, 3) AS BINARY(3)) AS DECIMAL(5, 2)) AS FLD4,
INTERPRET(CAST(SUBSTR(WS_DTAQ_MESSAGE, 17, 4) AS BINARY(4)) AS DECIMAL(7, 2)) AS FLD5,
INTERPRET(CAST(SUBSTR(WS_DTAQ_MESSAGE, 21, 8) AS BINARY(8)) AS NUMERIC(8, 5)) AS FLD6,
INTERPRET(CAST(SUBSTR(WS_DTAQ_MESSAGE, 29, 6) AS BINARY(6)) AS NUMERIC(6, 3)) AS FLD7,
INTERPRET(CAST(SUBSTR(WS_DTAQ_MESSAGE, 35, 3) AS BINARY(3)) AS NUMERIC(3, 0)) AS FLD8,
INTERPRET(CAST(SUBSTR(WS_DTAQ_MESSAGE, 38, 5) AS BINARY(5)) AS NUMERIC(5, 2)) AS FLD9''')

        output = generate_substr_from_file('input2.txt')
        self.assertEqual(output,
'''CAST(SUBSTR(WS_DTAQ_MESSAGE, 1, 3) AS CHAR(3) CCSID 37) AS FLD1,
CAST(SUBSTR(WS_DTAQ_MESSAGE, 4, 5) AS CHAR(5) CCSID 37) AS FLD2_1,
CAST(SUBSTR(WS_DTAQ_MESSAGE, 9, 5) AS CHAR(5) CCSID 37) AS FLD2_2,
CAST(SUBSTR(WS_DTAQ_MESSAGE, 14, 5) AS CHAR(5) CCSID 37) AS FLD2_3,
CAST(SUBSTR(WS_DTAQ_MESSAGE, 19, 2) AS CHAR(2) CCSID 37) AS FLD3A_1,
CAST(SUBSTR(WS_DTAQ_MESSAGE, 21, 3) AS CHAR(3) CCSID 37) AS FLD3B_1,
CAST(SUBSTR(WS_DTAQ_MESSAGE, 24, 2) AS CHAR(2) CCSID 37) AS FLD3A_2,
CAST(SUBSTR(WS_DTAQ_MESSAGE, 26, 3) AS CHAR(3) CCSID 37) AS FLD3B_2,
CAST(SUBSTR(WS_DTAQ_MESSAGE, 29, 5) AS CHAR(5) CCSID 37) AS FLD4''')

        output = generate_substr_from_file('input3.txt')
        self.assertEqual(output,
'''CAST(SUBSTR(WS_DTAQ_MESSAGE, 1, 10) AS CHAR(10) CCSID 37) AS TEXT,
INTERPRET(CAST(SUBSTR(WS_DTAQ_MESSAGE, 11, 7) AS BINARY(7)) AS NUMERIC(7, 2)) AS ZONED_POS,
INTERPRET(CAST(SUBSTR(WS_DTAQ_MESSAGE, 18, 7) AS BINARY(7)) AS NUMERIC(7, 2)) AS ZONED_NEG,
INTERPRET(CAST(SUBSTR(WS_DTAQ_MESSAGE, 25, 4) AS BINARY(4)) AS DECIMAL(7, 2)) AS PACKED_POS,
INTERPRET(CAST(SUBSTR(WS_DTAQ_MESSAGE, 29, 4) AS BINARY(4)) AS DECIMAL(7, 2)) AS PACKED_NEG,
INTERPRET(CAST(SUBSTR(WS_DTAQ_MESSAGE, 33, 4) AS BINARY(4)) AS INTEGER) AS BINARY_POS,
INTERPRET(CAST(SUBSTR(WS_DTAQ_MESSAGE, 37, 4) AS BINARY(4)) AS INTEGER) AS BINARY_NEG''')
